version: '3.8'
services:
  angular-app:
    build:
      context: ./price-peeker-front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  nestjs-app:
    build:
      context: ./price-peeker
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    networks:
      - app-network

networks:
  app-network:
